language: ruby
cache: bundler
rvm:
  - 1.9.3-p484
bundler_args: --without development poirot
services:
  - elasticsearch
before_script:
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
