mobile_id: off
host: localhost:3000

crystal_api_server: 'crystal-api-server/bin/release/darwin-x86_64/all'
plugins:
  public_collection: on
  snapshot: on
  channels: off
  reminders: on
  alerts: on
  fred_api: on
  csd_api: on

